### ISSUE TITLE
Add user and userdomain

### ISSUE THREAD

**Issue by tonybaloney** [pytest-dev/pytest-nunit#11]
See https://github.com/tonybaloney/pytest-nunit/blob/master/pytest_nunit/nunit.py#L76-L77

Also ensure this has a toggle to disable, incase someone wants to hide this info

**Comment by Williano** [comment]
I am happy to work on this

**Comment by tonybaloney** [comment]
@Williano are you able to raise a PR for the code we reviewed?

**Comment by Williano** [comment]
No Please. I was having issues when I tried to push my branch to the repo

**Comment by Williano** [comment]
remote: Permission to pytest-dev/pytest-nunit.git denied to Williano.
fatal: unable to access 'https://github.com/pytest-dev/pytest-nunit.git/': The requested URL returned error: 403

This is the error I get when I try to push

**Comment by tonybaloney** [comment]
@Williano If you're getting this on the git shell, it's because you're trying to push here, not to your fork.

```
git remote get-url origin
```
Says `https://github.com/pytest-dev/pytest-nunit.git/`? That's wrong.

Create another remote against your fork (using `git@github.com:williano/pytest-nunit.git` for SSH connections or `https://github.com/williano/pytest-nunit.git` for HTTPS)

```
git remote add me git@github.com:williano/pytest-nunit.git
git push --set-upstream me master
```

**Comment by Williano** [comment]
I have done that and I have opened a pull request for you to merge my branch.

Thank you for your help and guidance. I really appreciate it.
