### ISSUE TITLE
Test `dist` in pytest with plugin

### ISSUE THREAD

**Issue by tonybaloney** [pytest-dev/pytest-nunit#13]
Add an integration test that validates this plugin works with `dist`.

**Comment by mei-li** [comment]
Hi there, me and @swany91 wanna have a look on it

**Comment by mei-li** [comment]
Seems that when running it with `looponfailing` mode
`python -m pytest tests -v --nunit-xml=test-results.xml -f` with python 3.6.7
it doesn't stop rerunning the tests even if there is no change in the files

**Comment by tonybaloney** [comment]
Resolved in #25 and #24

**Comment by tonybaloney** [comment]
thanks @mei-li and @swany91
