### ISSUE TITLE
Option to omit attachments for successful tests

### ISSUE THREAD

**Issue by zooba** [pytest-dev/pytest-nunit#22]
I have a project that generates large files for each test case (approx. fuzz testing). These files are irrelevant if the test passes, but if it succeeds, I'd like to collect the file.

In order to save myself both GB of upload/storage, and having to `try/except AssertionError` around all my tests, can we have an option to drop attachments from successful tests?

(I'm happy to add it, though it's not immediately obvious where it should go. Does [this](https://github.com/pytest-dev/pytest-nunit/blob/master/pytest_nunit/plugin.py#L110) get called after each test?)

**Comment by tonybaloney** [comment]
this is a good idea, it should go around the `pytest_sessionfinish` stage, because at that stage the resolution has been collected and resolved.

The configuration should be an enum like:
- all 
- only pass
- only fail
- fail and xfail

**Comment by tonybaloney** [comment]
note: the upload doesn't happen in the plugin, the XML just contains a path to the attachment and the UI does the rest of the work

**Comment by tonybaloney** [comment]
Implemented in #34. Will be released in 0.4.0
