### ISSUE TITLE
Failure when no tests were run in a module

### ISSUE THREAD

**Issue by zooba** [pytest-dev/pytest-nunit#41]
If a test run ends with no tests having been tried (for example, because the module fails to import), `pytest_sessionfinish` fails by trying to find the min/max of an empty list.

In this case, reporting 0 should be fine. (PR coming)

**Comment by zooba** [comment]
Okay, so it's not quite as simple as the module failing to import. I have my own repro that I can't share, where it seems to be because the module won't import (though it's a... complicated... import), but a trivial one in the test suite doesn't seem to do it.

**Comment by tonybaloney** [comment]
Confirmed, I have the same issue
