### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest-nunit#46]
👋 I don't have release tokens so one of you two will have to do this (@tonybaloney @nicoddemus)

I'd like to release 0.6.0 which has the following changes (from what I can see on master):
- fix unicode escapes in cdata (#39)
- fix start/stop time calculation (#42)
- dropping support for python3.4 (can't test this in CI any more) (#45)
- dropping support for old xdist versions (#44)

**Comment by tonybaloney** [comment]
I'll do it

**Comment by tonybaloney** [comment]
Done. & tagged
