### ISSUE TITLE
Function outdated: add_nunit_attachment

### ISSUE THREAD

**Issue by webshoptest** [pytest-dev/pytest-nunit#58]
add_nunit_attachment can't be used as documented
`add_nunit_attachment(path, "peanut butter jelly time")`

> Fixture "add_nunit_attachment" called directly. Fixtures are not meant to be called directly,
> but are created automatically when test functions request them as parameters.
> See https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and
> https://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.

**Comment by asottile** [comment]
I suspect you're confused -- it's supposed to be used as a fixture [as documented](https://github.com/pytest-dev/pytest-nunit#add_nunit_attachment) and the error message you're seeing is because you're not doing that
