### ISSUE TITLE
Unable to add attachment in teardown

### ISSUE THREAD

**Issue by jfp1992** [pytest-dev/pytest-nunit#70]
This may not be a problem with the library, so this may be more of an ask for help, anyway,

I have your basic example working, I am able to upload attachments when put in the test itself, but if I try and add attachment using the teardown method it doesn't work.

Any ideas why this is?

I tried in both a teardown function in the test file and in an auto-use function in the config (after yield) - both didn't work

**Comment by robcam73** [comment]
I am having the same issue, although I expect it is simply not understanding how to use it. Whatever I do, it just tells me "Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters."

Can anyone explain how to use "add_nunit_attachment" please?

**Comment by jfp1992** [comment]
> I am having the same issue, although I expect it is simply not understanding how to use it. Whatever I do, it just tells me "Fixtures are not meant to be called directly, but are created automatically when test functions request them as parameters."
> 
> Can anyone explain how to use "add_nunit_attachment" please?

I've had to add this to every single test I create
```
def test_create_new_report(page: Page, path, add_nunit_attachment):
    add_nunit_attachment(path, "no desc")
```

"path" is a fixture I created that will return the path to the attachment generated by the test, in my case I am attaching a trace.zip from playwright. So I build a path to match that format.

It would be nice to have some clearer documentation, even if it said, you have to put it in each test and won't work as a setup/teardown sort of thing.

Would be great if this could be a global thing, having to repeat myself isn't nice

**Comment by jfp1992** [comment]
This worked for me: 

in conftest.py:
@pytest.fixture
def teardown(page, add_nunit_attachment, path, context):
    yield
    add_nunit_attachment(path, "description")

**Comment by jfp1992** [comment]
> 

You will need to pip install pytest-nunit

**Comment by jfp1992** [comment]
> Thanks. Probably another stupid question, but what do I need to import to get it to add the fixture. If I run pytest it seems to fail because add_nunit_attachment isn't know. I have installed the module and tried adding import pytest.unit but that doesn't seem to help. Sorry , I am very new to python and pytest

pip install pytest-nunit
