### ISSUE TITLE
Add locale and uiculture properties

### ISSUE THREAD

**Issue by tonybaloney** [pytest-dev/pytest-nunit#9]
See https://github.com/tonybaloney/pytest-nunit/blob/master/pytest_nunit/nunit.py#L54-L56

Need a Python 2.7-3.7, cross platform way of getting system locale and uiculture

**Comment by terrameijar** [comment]
@tonybaloney I'm interested in working on this. Just to confirm, the system locale, `culture` and `uiculture` are the same thing..yes?

**Comment by tonybaloney** [comment]
they would be the same thing since there is no UI. It should be a RFC 4646 language code, e.g. `en-US`
